## BASIC , INTERMEDIATE , ADVANCE LEVEL

1. Write a Python program to check if a given number is positive or negative.

In [48]:
a = int(input('enter the number'))
if a<0:
    print('number is negative')
else:
    print('number is positive')

enter the number 4


number is positive


2. Create a program that determines if a person is eligible to vote based on their age.

In [50]:
age = int(input('enter the age'))
if age<18:
    print('person not elligible for vote')
else:
    print('person is elligible for vote')

enter the age 5


person not elligible for vote


3. Develop a program to find the maximum of two numbers using if-else statements.

In [51]:
a = int(input('enter 1 the number'))
b = int(input('enter 2the number'))
if max(a,b):
    result = max(a,b)
    print('the max number is',result)

enter 1 the number 5
enter 2the number 7


the max number is 7


4. Write a Python script to classify a given year as a leap year or not.

In [52]:
year=int(input('enter the year'))
if year%4==0:
    print('year is leap year')
else:
    print('year is not leap year')

enter the year 2018


year is not leap year


5. Create a program that checks whether a character is a vowel or a consonant.

In [14]:
char = input('enter the character')
if char=='a' or char=='e' or char=='i' or char=='o' or char=='u':
    print(char,'is a vowels')
else:
    print(char,'consonent')

enter the character a


a is a vowels


6. Implement a program to determine whether a given number is even or odd.

In [17]:
num = int(input('enter the number'))
if num %2==0:
    print('number is even')
else:
    print('number is odd')

enter the number 3


number is odd


7. Write a Python function to calculate the absolute value of a number without using the `abs()` function.


In [28]:
import math

def absolute_value(num):
    """This function returns the absolute
    value of the entered number"""

    return math.sqrt(num ** 2)


print(absolute_value(10)) 
print(absolute_value(-20)) 
print(absolute_value(0)) 

10.0
20.0
0.0


8. Develop a program that determines the largest of three given numbers using if-else statements.

In [34]:
a = 23,56,23
if max(a):
    print('the largest of given number is ',max(a))
else:
    print('nothing')

the largest of given number is  56


9. Create a program that checks if a given string is a palindrome.

In [42]:
s='mom'
if s[::-1]==s:
    print('palindrome')
else:
    print('not palindrome')

palindrome


10. Write a Python program to calculate the grade based on a student's score.

In [50]:
num = int(input('enter the number'))
if num<=30:
    print('c grade')
elif num<=60:
    print('b grade')
elif num<=80:
    print('b+ grade')
else:
    print('A+ grade')

enter the number 82


A+ grade


11. Write a program to find the largest among three numbers using nested if-else statements.

In [52]:
a= 30
b= 40
c = 50
if a>b and a>c:
    largest=a
elif b>c:
    largest=b
else:
    largest=c
print(largest, "is the largest of three numbers.")

50 is the largest of three numbers.


12. Implement a program to determine if a triangle is equilateral, isosceles, or scalene.

In [55]:
x = 8 
y =7
z =9
if x==y==z:
    print('equilateral triangle')
elif x==y or y==z or z==x :
    print('isoselous triangle')
else:
    print('scalence')

scalence


13. Develop a program that checks if a year is a leap year and also if it is a century year.

In [63]:

  
def find_century(year):
    

    if (year <= 0):
        print("0 and negative is not allow for a year")
          

    elif (year <= 100):
        print("1st century")
    elif (year % 100 == 0):
        print(year // 100,"century")
    else:
        print(year // 100 + 1,"century")
year= 2001
find_century(year)

21 century


14. Write a Python script to determine if a number is positive, negative, or zero.

In [68]:
num = int(input('enter the number'))
if num>0:
    print('positive number')
elif num<0:
    print('negative number')
else:
    num==0
    print('zero')

enter the number 9


positive number


15. Create a program to check if a person is a teenager (between 13 and 19 years old).

In [71]:
age = int(input('enter the age'))
if age<=13 or age<=19:
    print('teenager')
else:
    print('not teenager')
    

enter the age 20


not teenager


17. Write a Python program to calculate the roots of a quadratic equation.

In [73]:
print("Equation: ax^2 + bx + c ")
a=int(input("Enter a: "))
b=int(input("Enter b: "))
c=int(input("Enter c: "))
d=b**2-4*a*c
d1=d**0.5
if(d<0):
    print("The roots are imaginary. ")
else:
    r1=(-b+d1)/2*a
    r2=(-b-d1)/2*a
    print("The first root: ",round(r1,2))
    print("The second root: ",round(r2,2))

Equation: ax^2 + bx + c 


Enter a:  4
Enter b:  5
Enter c:  5


The roots are imaginary. 


18. Implement a program to determine the day of the week based on a user-provided number (1 for Monday, 2
for Tuesday, etc.).

In [76]:
day = input('enter the day')
if day=='monday':
    print('1')
elif day=='tuesday':
    print('2')
elif day=='wednesday':
    print('3')
elif day=='thursday':
    print('4')
elif day=='friday':
    print('5')
elif day=='saturday':
    print('6')
else:
    day=='sunday'
    print('7')
        

enter the day tuesday


2


20. Develop a program that checks if a given number is prime or not using nested if-else statements.

In [78]:
num = int(input('enter the number'))
if num%2!=0:
    print('prime number')
else:
    print('not a prime number')

enter the number 5


prime number


## Elif Statements:

21. Write a Python program to assign grades based on different ranges of scores using elif statements.

In [2]:
marks= int(input('enetr the marks'))
if marks<=30:
    print('c grade')
elif marks<=60:
    print('b grade')
elif marks<=80:
    print('B grade')
else:
    marks<100
    print('A grade')

enetr the marks 90


A grade


22. Implement a program to determine the type of a triangle based on its angles.

In [9]:
a = int(input('side a'))
b = int(input('side b'))
c = int(input('side c'))
if a==b and b==c:
    print('equilateral triagle')
elif a==b or b==c or a==c:
    print('Triangle is Isosceles.')
else:
    print('Triangle is Scalane')

side a 2
side b 4
side c 6


Triangle is Scalane


23. Develop a program to categorize a given person's BMI into underweight, normal, overweight, or obese using
elif statements.

In [17]:
weight=int(input('enter weight'))
if weight<=60:
    print('Bmi is normal')
elif weight>=80:
    print('Bmi is overwight')
else:
    weight>=100
    print('Bmi is onese')

enter weight 40


Bmi is normal


24. Create a program that determines whether a given number is positive, negative, or zero using elif
statements.

In [22]:
num = int(input('enter the number'))
if num<0:
    print('negative')
elif num>0:
    print('positive')
else:
    num=0
    print('zero')

enter the number 90


positive


25. Write a Python script to determine the type of a character (uppercase, lowercase, or special) using elif
statements.

In [28]:
string =input('enter the string')
if string.upper() in string:
    print('uppercase')
elif string.lower() in string:
    print('lowercase')
else:
    '@' or '#' or '$' or '%' or '&' in string
    print('special char')

enter the string AVICHAL


uppercase


26. Implement a program to calculate the discounted price based on different purchase amounts using elif
statements.

In [31]:
p=int(input('Enter purchase amount '))
if p<=5000:
    dis=0
elif p>5000 and p<=10000:
    dis=(p-5000)*(10/100.0)
elif p>10000 and p<=20000:
    dis=(p-10000)*(20/100.0)
elif p>20000 and p<=30000:
    dis=(p-20000)*(30/100.0)
else:
    dis=(p-30000)*(40/100.0)

print('Discount Amount = {:.2f}'.format(dis))
print('Net Bill Amount = {:.2f}'.format(p-dis))

Enter purchase amount  6000


Discount Amount = 100.00
Net Bill Amount = 5900.00


27. Develop a program to calculate the electricity bill based on different consumption slabs using elif
statements.

In [33]:
def calculateBill(units):
 
    if (units <= 100):
      
        return units * 10;
     
    elif (units <= 200):
     
        return ((100 * 10) +
                (units - 100) * 15);
     
    elif (units <= 300):
      
        return ((100 * 10) +
                (100 * 15) +
                (units - 200) * 20);
     
    elif (units > 300):
     
        return ((100 * 10) +
                (100 * 15) +
                (100 * 20) +
                (units - 300) * 25);
     
    return 0;
 

units = 250;
print(calculateBill(units));

3500


29. Write a Python script to determine the season based on a user-provided month using elif statements.

In [35]:
month = input("Input the month (e.g. January, February etc.): ")

if month in ('January', 'February', 'March'):
	season = 'winter'
elif month in ('April', 'May', 'June'):
	season = 'spring'
elif month in ('July', 'August', 'September'):
	season = 'summer'
else:
	season = 'autumn'

print("Season is",season)

Input the month (e.g. January, February etc.):  january


Season is autumn


30. Implement a program to determine the type of a year (leap or common) and month (30 or 31 days) using
elif statements.

In [37]:
year = int(input('enter the year'))
if year%4==0:
    print('leap year')
else:
    print('commom year')

enter the year 2016


leap year


## Basic Level:

1. Write a Python program that checks if a given number is positive, negative, or zero.
2. Create a program to determine if a person is eligible to vote based on their age.
3. Write a program to find the maximum of two given numbers using conditional statements.
4. Develop a program that calculates the grade of a student based on their exam score.
5. Create a program that checks if a year is a leap year or not.
6. Write a program to classify a triangle based on its sides' lengths.
7. Build a program that determines the largest of three given numbers.
8. Develop a program that checks whether a character is a vowel or a consonant.
9. Create a program to calculate the total cost of a shopping cart based on discounts.
10. Write a program that checks if a given number is even or odd.

1. Write a Python program that checks if a given number is positive, negative, or zero.

In [3]:
num = int(input('enter the number'))
if num<0:
    print('negative')
elif num>0:
    print('positive')
else :
    print('zero')

entyer the number 12


positive


2. Create a program to determine if a person is eligible to vote based on their age.

In [7]:
age = int(input('enter the age'))
if age >= 18:
    print('eligible to vote')
else:
    print('not eligible to vote')

enter the age 19


eligible to vote


3. Write a program to find the maximum of two given numbers using conditional statements.

In [10]:
num1 = int(input('enter the number 1'))
num2 = int(input('enter the number 2'))
if max(num1,num2):
    print('maximum of two is',max(num1,num2))


enter the number 1 56
enter the number 2 67


maximum of two is 67


4. Develop a program that calculates the grade of a student based on their exam score.

In [14]:
marks = int(input('enter the marks'))
if marks<=30:
    print('student get c grade')
elif marks>=30 and marks<=60:
    print('student get b grade')
elif marks>=80:
    print('student get b+ grade')
else:
    marks>=90
    print('student get A+ grade')

enter the marks 20


student get c grade


5. Create a program that checks if a year is a leap year or not

In [17]:
year = int(input('enter the year'))
if year%4==0:
    print('year is leap year')
else:
    print('year is not leap year')

enter the year 2018


year is not leap year


6. Write a program to classify a triangle based on its sides' lengths.

In [23]:
xside = int(input('enter the side 1'))
yside = int(input('enter the side 2'))
zside = int(input('enter the side 3'))
if xside==yside and yside==zside:
    print('triangle is equlateral')
elif xside==yside and xside==zside and yside==zside:
    print('triangle is Isosceles Triangle: ')
else:
    print('Scalene Triangle')

enter the side 1 7
enter the side 2 7
enter the side 3 7


triangle is equlateral


7. Build a program that determines the largest of three given numbers.

In [25]:
num1 = int(input('enter the num 1'))
num2 = int(input('enter the num 2'))
num3 = int(input('enter the num 3'))
if max(num1,num2,num3):
    print('the max of three number is',max(num1,num2,num3))

enter the num 1 7
enter the num 2 8
enter the num 3 24


the max of three number is 24


8. Develop a program that checks whether a character is a vowel or a consonant

In [8]:
ch = input("Enter a character: ")

if(ch=='A' or ch=='a' or ch=='E' or ch =='e' or ch=='I'
 or ch=='i' or ch=='O' or ch=='o' or ch=='U' or ch=='u'):
    print(ch, "is a Vowel")
else:
    print(ch, "is a Consonant")

Enter a character:  p


p is a Consonant


In [ ]:
number = int(input('enter the number'))
if number%2==0:
    print('even number')
else:
    print('odd number')

enter the number 73


odd number


 # Intermediate Level:

11. Write a program that calculates the roots of a quadratic equation .
12. Create a program that determines the day of the week based on the day number (1-7).
13. Develop a program that calculates the factorial of a given number using recursion.
14. Write a program to find the largest among three numbers without using the `max()` function.
15. Create a program that simulates a basic ATM transaction menu.
16. Build a program that checks if a given string is a palindrome or not.
17. Write a program that calculates the average of a list of numbers, excluding the smallest and largest values.
18. Develop a program that converts a given temperature from Celsius to Fahrenheit.
19. Create a program that simulates a basic calculator for addition, subtraction, multiplication, and division.
20. Write a program that determines the roots of a cubic equation using the Cardano formula.

11. Write a program that calculates the roots of a quadratic equation .

In [ ]:
print("Equation: ax^2 + bx + c ")
a=int(input("Enter a: "))
b=int(input("Enter b: "))
c=int(input("Enter c: "))
d=b**2-4*a*c
d1=d**0.5
if(d<0):
    print("The roots are imaginary. ")
else:
    r1=(-b+d1)/2*a
    r2=(-b-d1)/2*a
    print("The first root: ",round(r1,2))
    print("The second root: ",round(r2,2))

Equation: ax^2 + bx + c 


12. Create a program that determines the day of the week based on the day number (1-7).

In [1]:
day = input('enter the day')
if day=='monday':
    print('1')
elif day=='tuesday':
    print('2')
elif day=='wednesday':
    print('3')
elif day=='thursday':
    print('4')
elif day=='friday':
    print('5')
elif day=='saturday':
    print('6')
else:
    day=='sunday'
    print('7')
        

enter the day monday


1


In [2]:
num1 = int(input('enter the number 1'))
num2 = int(input('enter the number 2'))
num3 = int(input('enter the number 3'))
if (num1 >= num2) and (num1 >= num3):
    largest = num1
elif (num2 >= num1) and (num2 >= num3):
    largest = num2
else:
    largest = num3

print("The largest number is", largest)

enter the number 1 8
enter the number 2 7
enter the number 3 90


The largest number is 90


15. Create a program that simulates a basic ATM transaction menu.

In [13]:
class bank_account:
    balance = 100
    def __init__(self,balance):
        self.balance=balance
    def deposit(self,amount):
        return self.balance+amount
    def withdraw(self,amount):
        return self.balance-amount
    def balance(self,balance):
        self.balance


In [14]:
bank_account=bank_account(1000)

In [15]:
bank_account.deposit(1000)

2000

In [16]:
bank_account.withdraw(500)

500

16. Build a program that checks if a given string is a palindrome or not.

In [32]:
st= 'mom'
if st[::-1]==st:
    print('string is palindrom')
else:
    print('string is not palindrome')

string is palindrom


17. Write a program that calculates the average of a list of numbers, excluding the smallest and largest values.

18. Develop a program that converts a given temperature from Celsius to Fahrenheit.

In [33]:
celsius = 37.5
fahrenheit = (celsius * 1.8) + 32
print('%0.1f degree Celsius is equal to %0.1f degree Fahrenheit' %(celsius,fahrenheit))

37.5 degree Celsius is equal to 99.5 degree Fahrenheit


19. Create a program that simulates a basic calculator for addition, subtraction, multiplication, and division

In [40]:
num1 = int(input('enter the number 1'))
num2 = input('enter *,+,-,%')
num3 = int(input('enter the number 2'))
 
if num2== '+':
    print(num1+num3)
elif num2=='-':
    print(num1-num3)
elif num2=='*':
    print(num1*num3)
elif num2=='%':
    print(num1%num3)
else:
    print("invalid operation")

enter the number 1 90
enter *,+,-,% -
enter the number 2 9


81


20. Write a program that determines the roots of a cubic equation using the Cardano formula.

In [41]:
def solve(a,b,c,d):
    Q = (3*a*c - (b**2)) / (9*(a**2))
    R = (9*a*b*c - 27*(a**2)*d - 2*(b**3)) / (54*(a**3))
    D = (Q**3) + (R**2)
    S = (R + (D**(1/2)))**(1/3)
    T = (R - (D**(1/2)))**(1/3)

    x1 = S + T - (b/(3*a))
    x2 = -((S + T)/2) - (b/(3*a)) + 0.5j * (3**(1/2)) * (S - T)
    x3 = -((S + T)/2) - (b/(3*a)) - 0.5j * (3**(1/2)) * (S - T)

    return (x1,x2,x3)

In [43]:
solve(1,2,3,4)

((0.42697045480630835+1.199502715028224j),
 (-0.17468540428030588-0.8521365428250519j),
 (-2.252285050526002-0.3473661722031721j))

# Advanced Level:

21. Create a program that calculates the income tax based on the user's income and tax brackets.
22. Write a program that simulates a rock-paper-scissors game against the computer.
23. Develop a program that generates a random password based on user preferences (length, complexity).
24. Create a program that implements a simple text-based adventure game with branching scenarios.
25. Build a program that solves a linear equation for x, considering different cases.
26. Write a program that simulates a basic quiz game with multiple-choice questions and scoring.
27. Develop a program that determines whether a given year is a prime number or not.
28. Create a program that sorts three numbers in ascending order using conditional statements.
29. Build a program that determines the roots of a quartic equation using numerical methods.
30. Write a program that calculates the BMI (Body Mass Index) and provides health recommendations based
on the user's input.

21. Create a program that calculates the income tax based on the user's income and tax brackets.

In [46]:
income=int(input('enter income'))
if income <= 250000:  #2 Lakh 50 thousand
    tax = 0

elif income <= 500000: #5 Lakh
    tax = (income - 250000) * 0.05

elif income <= 750000: #7 lakh 50 thousand
    tax = (income - 500000) * 0.10 + 12500 

elif income <= 1000000: #10 Lakh
    tax = (income - 750000) * 0.15 + 37500 

elif income <= 1250000: #12 lakh 50 thousand
    tax = (income - 1000000) * 0.20 + 75000 

elif income <= 1500000: #15 lakh
    tax = (income - 1250000) * 0.25 + 125000 

else:
    tax = (income - 1500000) * 0.30 + 187500

print("you owe", tax, "Rupees in tax!")

enter income 10000000


you owe 2737500.0 Rupees in tax!


22. Write a program that simulates a rock-paper-scissors game against the computer.

In [ ]:
from random import randint

#create a list of play options
t = ["Rock", "Paper", "Scissors"]

#assign a random play to the computer
computer = t[randint(0,2)]

#set player to False
player = False

while player == False:
#set player to True
    player = input("Rock, Paper, Scissors?")
    if player == computer:
        print("Tie!")
    elif player == "Rock":
        if computer == "Paper":
            print("You lose!", computer, "covers", player)
        else:
            print("You win!", player, "smashes", computer)
    elif player == "Paper":
        if computer == "Scissors":
            print("You lose!", computer, "cut", player)
        else:
            print("You win!", player, "covers", computer)
    elif player == "Scissors":
        if computer == "Rock":
            print("You lose...", computer, "smashes", player)
        else:
            print("You win!", player, "cut", computer)
    else:
        print("That's not a valid play. Check your spelling!")
    #player was set to True, but we want it to be False so the loop continues
    player = False
    computer = t[randint(0,2)]

24. Create a program that implements a simple text-based adventure game with branching scenarios.

In [1]:
def introScene():
    if __name__ == "__main__":
        while True:
            print("Welcome to the Adventure Game!")
            print("As an avid traveler, you have decided to visit the Catacombs of Paris.")
            print("However, during your exploration, you find yourself lost.")
            print("You can choose to walk in multiple directions to find a way out.")
            print("Let's start with your name: ")
            name = input()
            print("Good luck, " +name+ ".")
            introScene()

In [ ]:
introScene()

Welcome to the Adventure Game!
As an avid traveler, you have decided to visit the Catacombs of Paris.
However, during your exploration, you find yourself lost.
You can choose to walk in multiple directions to find a way out.
Let's start with your name: 


 AVICHAL


Good luck, AVICHAL.
Welcome to the Adventure Game!
As an avid traveler, you have decided to visit the Catacombs of Paris.
However, during your exploration, you find yourself lost.
You can choose to walk in multiple directions to find a way out.
Let's start with your name: 


 avichal


Good luck, avichal.
Welcome to the Adventure Game!
As an avid traveler, you have decided to visit the Catacombs of Paris.
However, during your exploration, you find yourself lost.
You can choose to walk in multiple directions to find a way out.
Let's start with your name: 


25. Build a program that solves a linear equation for x, considering different cases.

In [3]:
from sympy import symbols, Eq, solve
  

x, y, z = symbols('x,y,z')
  

eq1 = Eq((x+y+z), 1)
print("Equation 1:")
print(eq1)
  
eq2 = Eq((x-y+2*z), 1)
print("Equation 2")
print(eq2)
  
eq3 = Eq((2*x-y+2*z), 1)
print("Equation 3")
  

print("Values of 3 unknown variable are as follows:")
print(solve((eq1, eq2, eq3), (x, y, z)))

Equation 1:
Eq(x + y + z, 1)
Equation 2
Eq(x - y + 2*z, 1)
Equation 3
Values of 3 unknown variable are as follows:
{x: 0, y: 1/3, z: 2/3}


26. Write a program that simulates a basic quiz game with multiple-choice questions and scoring.

In [8]:
print('welcome to quiz')
print('NOTE: if your spelling is incorrect then it is considered as wrong answer')
ques=0
score = 0
playing=input('do you want to play')
if playing=='yes':
    ques+=1
    question=input(f'what is CPU stand for?')
if question=='central processing unit':
    score+=1
    print('correct! you got 1 point')
else:
    print('Incorrect!')

welcome to quiz
NOTE: if your spelling is incorrect then it is considered as wrong answer


do you want to play yes
what is CPU stand for? central processing unit


correct! you got 1 point


27. Develop a program that determines whether a given year is a prime number or not.

In [11]:
year = int(input('enter the year'))
if year%2!=0:
    print('year is a prime year')
else:
    print('year is no prime year')

enter the year 2013


year is a prime year


28. Create a program that sorts three numbers in ascending order using conditional statements.

In [12]:
number=[23343,3445,212]
if sorted(number):
    print(sorted(number))

[212, 3445, 23343]


29. Build a program that determines the roots of a quartic equation using numerical methods.

In [30]:
import math
 
# Prints roots of quadratic equation
# ax*2 + bx + x
def findRoots(a, b, c):
 
    # If a is 0, then equation is
    # not quadratic, but linear
    if a == 0:
        print("Invalid")
        return -1
    d = b * b - 4 * a * c
    sqrt_val = math.sqrt(abs(d))
 
    if d > 0:
        print("Roots are real and different ")
        print((-b + sqrt_val)/(2 * a))
        print((-b - sqrt_val)/(2 * a))
    elif d == 0:
        print("Roots are real and same")
        print(-b / (2*a))
    else:  # d<0
        print("Roots are complex")
        print(- b / (2*a), " + i", sqrt_val / (2 * a))
        print(- b / (2*a), " - i", sqrt_val / (2 * a))
 
 
# Driver Program
if __name__ == '__main__':
    a = 1
    b = -7
    c = 12
     
    # Function call
    findRoots(a, b, c)

Roots are real and different 
4.0
3.0


# Challenge Level:

31. Create a program that validates a password based on complexity rules (length, characters, etc.).
32. Develop a program that performs matrix addition and subtraction based on user input.
33. Write a program that calculates the greatest common divisor (GCD) of two numbers using the Euclidean
algorithm.
34. Build a program that performs matrix multiplication using nested loops and conditional statements.
35. Create a program that simulates a basic text-based tic-tac-toe game against the computer.
36. Write a program that generates Fibonacci numbers up to a specified term using iterative methods.
37. Develop a program that calculates the nth term of the Fibonacci sequence using memoization.
38. Create a program that generates a calendar for a given month and year using conditional statements.
39. Build a program that simulates a basic text-based blackjack game against the computer.
40. Write a program that generates the prime factors of a given number using trial division.

31. Create a program that validates a password based on complexity rules (length, characters, etc.).

In [34]:
string=input('enter the char')
special=input('enter special char')
number=int(input('enter number'))
if string==string.upper():
    print('valid password')
elif special=="@#$*":
    print('valid password')
elif number<10:
    print('valid password')
else:
    print('invalid pass word')

enter the char AVICHAjo*
enter special char 0909
enter number 434


invalid pass word


32. Develop a program that performs matrix addition and subtraction based on user input.

In [36]:
import numpy as np
A = np.array([[1, 2], [3, 4]])
B = np.array([[4, 5], [6, 7]])
 
print("Printing elements of first matrix")
print(A)
print("Printing elements of second matrix")
print(B)
 
# adding two matrix
print("Addition of two matrix")
print(np.add(A, B))

Printing elements of first matrix
[[1 2]
 [3 4]]
Printing elements of second matrix
[[4 5]
 [6 7]]
Addition of two matrix
[[ 5  7]
 [ 9 11]]


33. Write a program that calculates the greatest common divisor (GCD) of two numbers

In [37]:
import numpy as np
np.gcd(23,45)

1

34. Build a program that performs matrix multiplication 

In [39]:
import numpy as np
A = np.array([[1, 2], [3, 4]])
B = np.array([[4, 5], [6, 7]])
 
print("Printing elements of first matrix")
print(A)
print("Printing elements of second matrix")
print(B)
 
# adding two matrix
print("Addition of two matrix")
print(np.multiply(A, B))

Printing elements of first matrix
[[1 2]
 [3 4]]
Printing elements of second matrix
[[4 5]
 [6 7]]
Addition of two matrix
[[ 4 10]
 [18 28]]


36. Write a program that generates Fibonacci numbers up to a specified term using iterative methods.

In [41]:


nterms = int(input("How many terms? "))


n1, n2 = 0, 1
count = 0


if nterms <= 0:
    print("Please enter a positive integer")

elif nterms == 1:
    print("Fibonacci sequence upto",nterms,":")
    print(n1)

else:
    print("Fibonacci sequence:")
    while count < nterms:
        print(n1)
        nth = n1 + n2
       # update values
        n1 = n2
        n2 = nth
        count += 1

How many terms?  5


Fibonacci sequence:
0
1
1
2
3


38. Create a program that generates a calendar for a given month and year using conditional statements.

In [46]:
import calendar
y = int(input("Input the year : "))
m = int(input("Input the month : "))
print(calendar.month(y,m))


Input the year :  2089
Input the month :  7


     July 2089
Mo Tu We Th Fr Sa Su
             1  2  3
 4  5  6  7  8  9 10
11 12 13 14 15 16 17
18 19 20 21 22 23 24
25 26 27 28 29 30 31



40. Write a program that generates the prime factors of a given number using trial division.

In [47]:
def TrialDivision(N):
 

    i = 2
 

    k = int(N ** 0.5)
 
 
    while(i<= k):
 
      
        if(N % i == 0):
            return 0
        i += 1
 
    return 1
     
# Driver code
if __name__ == "__main__":
    N = 49
    p = TrialDivision(N)
 

    if(p):
        print("Prime")
    else:
        print("Composite")
        

Composite
